//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpdateManager.Languages {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UpdateManager.Languages.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Güncellemeleri Kontrol &amp;Et benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string CheckUpdates {
            get {
                return ResourceManager.GetString("CheckUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Güncellemeleri Kontrol Et benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string CheckUpdates_CA {
            get {
                return ResourceManager.GetString("CheckUpdates_CA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Geçerli Sürüm: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string CurrentVersion {
            get {
                return ResourceManager.GetString("CurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Doğrudan İndir benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DirectDownload {
            get {
                return ResourceManager.GetString("DirectDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İndirildi. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Downloaded {
            get {
                return ResourceManager.GetString("Downloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İndirilen dosya doğrulanmadı. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DownloadedFileDontTrue {
            get {
                return ResourceManager.GetString("DownloadedFileDontTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İndiriliyor... benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Güncellemeleri &amp;İndir benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DownloadUpdates {
            get {
                return ResourceManager.GetString("DownloadUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hata benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HATA: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ERROR_2 {
            get {
                return ResourceManager.GetString("ERROR_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Çıkış benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kurulum tamamlandı. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string InstallationCompleted {
            get {
                return ResourceManager.GetString("InstallationCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Güncellemeleri &amp;Kur benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string InstallUpdates {
            get {
                return ResourceManager.GetString("InstallUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Güncellemeleri Kur benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string InstallUpdates_CA {
            get {
                return ResourceManager.GetString("InstallUpdates_CA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Son Sürüm: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string LastVersion {
            get {
                return ResourceManager.GetString("LastVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Son Sürüm Tespit edilemedi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string LatestVersionNotDetected {
            get {
                return ResourceManager.GetString("LatestVersionNotDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yeni Bir Sürüm Mevcut. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lblANewVersionAva {
            get {
                return ResourceManager.GetString("lblANewVersionAva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Güncellemek istiyor musun? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lblANewVersionAva2 {
            get {
                return ResourceManager.GetString("lblANewVersionAva2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sürüm güncel. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string NoNewVersion {
            get {
                return ResourceManager.GetString("NoNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Klasörde &amp;göster benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string OpenFolder {
            get {
                return ResourceManager.GetString("OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toplam Boyut: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string TotalSize {
            get {
                return ResourceManager.GetString("TotalSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kaldırılıyor: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Uninstalling {
            get {
                return ResourceManager.GetString("Uninstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Güncelleme Yöneticisi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string UpdateManager {
            get {
                return ResourceManager.GetString("UpdateManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Doğrulama dosyası indirilemedi. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string VerificationFileNo {
            get {
                return ResourceManager.GetString("VerificationFileNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Evet benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
